### ISSUE TITLE
Server connection results in failed Handshake for potentially valid header.

### ISSUE THREAD

**Issue by carvefx** [sirn-se/websocket-php#107]
**Describe the bug**
While chromium-based browsers don't do this, other browsers, notably Firefox will set a 
`Connection: keep-alive, Upgrade` header on a websocket request. Due to the code in https://github.com/sirn-se/websocket-php/blob/v3.2-main/src/Server.php#L558 this leads to a failing handshake, unless the header is overwritten with just the Upgrade value.

Both raw request headers are tested on the latest (to date) versions of the browsers on a up to date Mac 15.3.1

Firefox 136.0
```
GET / HTTP/1.1
Host: localhost:3030
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:136.0) Gecko/20100101 Firefox/136.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br, zstd
Sec-WebSocket-Version: 13
Origin: http://localhost:3000
Sec-WebSocket-Protocol: graphql-transport-ws
Sec-WebSocket-Extensions: permessage-deflate
Connection: keep-alive, Upgrade
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: websocket
Sec-Fetch-Site: same-site
Pragma: no-cache
Cache-Control: no-cache
```

Chrome 133
```
GET ws://localhost:3030/ HTTP/1.1
Host: localhost:3030
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36
Upgrade: websocket
Origin: http://localhost:3000
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9,de;q=0.8
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Protocol: graphql-transport-ws
```

**How to reproduce**
I was able to reproduce either by just using a firefox browser connecting directly to the server or doing something like

```
brew install websocat
websocat ws://localhost:3030 \
  --header "Connection: keep-alive, Upgrade" \
  --header "Sec-WebSocket-Protocol: graphql-transport-ws"
```

**Workaround**
I was able to resolve the issue without forking the library by implementing a middleware for this case:

```
class ConnectionHeaderHandler implements ProcessHttpIncomingInterface, LoggerAwareInterface
{
    use LoggerAwareTrait;
    use StringableTrait;

    public function processHttpIncoming(ProcessHttpStack $stack, Connection $connection): MessageInterface
    {
        $request = $stack->handleHttpIncoming();

        if ($request instanceof ServerRequest && $request->hasHeader('Connection')) {
            $connectionHeader = trim($request->getHeaderLine('Connection'));
            $this->logger->debug("[connection-header-handler] Original Connection Header", ['Connection-Header' => $connectionHeader]);

            $lowerCasedHeader = strtolower($connectionHeader);
            if ($lowerCasedHeader == 'upgrade') {
                return $request;
            }

            if (str_contains($lowerCasedHeader, 'upgrade')) {
                $this->logger->debug("[connection-header-handler] Stripping Connection Header", ['Connection-Header' => $connectionHeader]);
                $request = $request->withHeader('Connection', 'Upgrade');
            }
        }

        return $request;
    }
}
```

**Question**
I'm not sure if this deserves to be addressed in `Websocket\Server` or my solution as an opt-in Middleware is good enough, but I'd be happy to attempt a PR at either options if this is desired by the maintainer. (Or at the very least document it somewhere)

Thanks for the amazing work on this library, bring php websockets back into the present!

**Comment by sirn-se** [comment]
Strange. This was fixed in [2.1.3](https://github.com/sirn-se/websocket-php/pull/40/files) but apparently the fix got lost along the way. I'll look into it.

**Comment by sirn-se** [comment]
Fix released as `v3.2.5`.

**Comment by carvefx** [comment]
Just tested it, and it looks like it's still not working -> I suspect the cause is the accidental reversing of the order of arguments in `str_contains`

little test example
```
<?php
	$connectionHeader = 'keep-alive, Upgrade';
            if (!str_contains('upgrade', strtolower($connectionHeader))) {
                var_dump('error, 426');
            } else {
              var_dump('success');
            }
?>
```

**Comment by sirn-se** [comment]
Your PR now available as `v3.2.6`, thanks for contributing!
